#!/bin/sh /etc/rc.common

/etc/preinit.d/scapi_utils.sh
USE_PROCD=1
START=70

start_service() {
        procd_open_instance
        procd_set_param command ntgr_ra_dce
        procd_set_param respawn
        procd_close_instance
}

