#!/bin/sh

dump_option_to_file()
{
	> $sysopt
	while read -r line; do
		if [ "${line:0:1}" == "Y" ]; then
		    echo "${line:2}" >> $sysopt
		fi
	done < "$1"
}

optfile="/var/syslog.option"
sysopt="/tmp/syslog.option"

while true; do
	dump_option_to_file $optfile; [ `grep -f $sysopt /var/log/ntgr.log | wc -l ` -gt 921 ] && mail full; sleep 10
done
