
CONFIG_PPTP=n
#CONFIG_BPA=y
CONFIG_RIP=y
CONFIG_NEW_WANDETECT=y

CONFIG_SINGLE_PROCESS_PPPOE=y

SAMBA_ENABLE_FLAG=y
CONFIG_MTOOLS=y
FTP_ACCESS_USB_FLAG=y


CONFIG_DLNA=y
INCLUDE_IPV6_FLAG=y


#ifeq ($(PROFILE),D6400)
#CONFIG_OPENVPN=y
#CONFIG_NTFS_3G=n
#ENABLE_VPN=n
#CONFIG_REMOTE_SMB_CONF=n
#endif

#ifeq ($(PROFILE),D6220)
#CONFIG_OPENVPN=y
#CONFIG_NTFS_3G=n
#ENABLE_VPN=n
#CONFIG_REMOTE_SMB_CONF=n
#endif

ifeq ($(PROFILE),RAX40)
CONFIG_OPENVPN=y
CONFIG_NTFS_3G=y
ENABLE_VPN=n
CONFIG_REMOTE_SMB_CONF=n
CONFIG_OPENDNS=y
CONFIG_CLOUD_XAGENT_CONF=y
endif

#ifeq ($(PROFILE),D6220v2)
#CONFIG_OPENVPN=y
#CONFIG_NTFS_3G=y
#ENABLE_VPN=n
#CONFIG_REMOTE_SMB_CONF=n
#CONFIG_OPENDNS=y
#endif
