# ******************************************************************************** #
#       Copyright (c) 2015                                                         #
#       Lantiq Beteiligungs-GmbH & Co. KG                                          #
#       Lilienthalstrasse 15, 85579 Neubiberg, Germany                             #
#       For licensing information, see the file 'LICENSE' in the root folder of    #
#        this software module.                                                     #
# *******************************************************************************  #

PKG_NAME := libBF

bins := libBF.so

CFLAGS += -std=gnu99

libBF.so_sources := $(wildcard *.c)
#libBF.so_ldflags := -lcal -lssl  -lscapi -lsysfapi

include make.inc
