/************************************************************************************
 
  	Copyright (c) 2015
	Lantiq Beteiligungs-GmbH & Co. KG
	Lilienthalstrasse 15, 85579 Neubiberg, Germany 
	For licensing information, see the file 'LICENSE' in the root folder of
	this software module.
 
************************************************************************************/

/************************************************************************************
 *		 File Name	:	ugw_notify_defs.h		    	    *
 *		 Description	:	notification id's for servd to inform about *
 *					sync/async				    *
 ************************************************************************************/


#ifndef _UGW_NOTIFY_DEFS_H
#define _UGW_NOTIFY_DEFS_H

/*! \file ugw_notify_defs.h
\brief This File contains SL's Notification list
*/
/** \defgroup HELP_COMMON_LIB Helper Library COMMON
*/
/* @{ */

/*! \enum NotifyDefs
    \brief Enum containing several Notifications that will be subscribed by SL's sent from hotplug, servd and several other daemons and utils.
*/
typedef enum {
	NOTIFY_DEFAULT_LAN_UP,		/*!< DEFAULT LAN UP NOTIFY */ 
	NOTIFY_DEFAULT_LAN_DOWN,	/*!< DEFAULT LAN DOWN NOTIFY */
	NOTIFY_DEFAULT_WAN_UP,		/*!< DEFAULT WAN UP NOTIFY */
	NOTIFY_DEFAULT_WAN_DOWN,	/*!< DEFAULT WAN DOWN NOTIFY */
	NOTIFY_DEFAULT_DSL_UP,		/*!< DEFAULT DSL UP NOTIFY */	
	NOTIFY_DEFAULT_DSL_DOWN,	/*!< DEFAULT DSL DOWN NOTIFY */	
	NOTIFY_DEFAULT_WWAN_UP,		/*!< DEFAULT WWAN UP NOTIFY */
	NOTIFY_DEFAULT_WWAN_DOWN,	/*!< DEFAULT WWAN DOWN NOTIFY */
	NOTIFY_FIRMWARE_UPGRADE_PRE,	/*!< FIREWALL UPGRADE PRE NOTIFY */
	NOTIFY_NTP_SYNC,	/*!< NTP SYNC NOTIFY */
	NOTIFY_NTP_SYNC_ERROR,	/*!< NTP SYNC ERROR NOTIFY */
	NOTIFY_INTERFACE_UP,	/*!< INTERFACE UP NOTIFY */
	NOTIFY_INTERFACE_DOWN,	/*!< INTERFACE DOWN NOTIFY */
	NOTIFY_INTERFACE_REGISTRATION,	/*!< INTERFACE REGISTRATION NOTIFY */
	NOTIFY_INTERFACE_DEREGISTRATION,	/*!< INTERFACE DEREGISTRATION NOTIFY */
	NOTIFY_WIFI_RADIO_STATUS_CHANGE,	/*!< WIFI RADIO STATUS NOTIFY */
	NOTIFY_WIFI_SSID_STATUS_CHANGE,		/*!< WIFI SSID STATUS NOTIFY */
	NOTIFY_WIFI_DEVICE_ASSOCIATED,		/*!< WIFI DEVICE ASSOCIATE  NOTIFY */
	NOTIFY_WIFI_WPS_ACTION,				/*!< WIFI WPS ACTION  NOTIFY */	
	NOTIFY_WIFI_WPS_NEW_AP_SETTINGS,	/*!< WIFI WPS NEW AP NOTIFY */
	NOTIFY_WIFI_WPS_STATUS,	 			/*!< WIFI WPS STATUS NOTIFY */
	NOTIFY_WIFI_UPDATE_PARAM,			/*!< WIFI UPDATE PARAM NOTIFY */	
	NOTIFY_WIFI_ENDPOINT_CONNECTED,			/*!< WIFI WPS ENDPOINT NOTIFY */
	NOTIFY_DSL_INTERFACE_STATUS,		/*!< DSL INTERFACE NOTIFY */
	NOTIFY_DSL_DATARATE_STATUS,			/*!< DSL DATARATE NOTIFY */
	NOTIFY_DSL_DATARATE_STATUS_US,		/*!< DSL DATARATE STATUS NOTIFY */
	NOTIFY_IPv6_PREFIX_UP,				/*!< IPv6 PREFIX UP NOTIFY */		
	NOTIFY_IPv6_PREFIX_DOWN,			/*!< IPv6 PREFIX DOWN NOTIFY */		
	NOTIFY_IPv6_RA_RECEIVED,			/*!< IPv6 RA RECEIVED NOTIFY */		
	NOTIFY_DSLITE_STATIC_UP,			/*!< DSLITE STATIC UP NOTIFY */		
	NOTIFY_DSLITE_DYNAMIC_UP,			/*!< DSLITE  DYANAMIC UP NOTIFY */			
	NOTIFY_INTERFACE_STATUS,			/*!< INTERFACE STATUS NOTIFY */	
	NOTIFY_IPADDRESS_CHANGE,			/*!< IPADDRESS CHANGE NOTIFY */	
	NOTIFY_ARP_CHANGE,					/*!< ARP CHANGE NOTIFY */	
	NOTIFY_ROUTE_CHANGE,				/*!< ROUTE CHANGE NOTIFY */	
	NOTIFY_DEFAULT_ROUTE_CHANGE,		/*!< DEFAULT ROUTE CHANGE NOTIFY */	
	NOTIFY_LAN_BR_INTERFACE_UP,			/*!< LAN BR INTERFACE UP NOTIFY */	
	NOTIFY_LAN_BR_INTERFACE_DOWN,		/*!< LAN BR INTERFACE DOWN NOTIFY */		
	NOTIFY_FIREWALL_PORT_OPEN,			/*!< FIREWALL PORT OPEN NOTIFY */	
	NOTIFY_FIREWALL_PORT_CLOSE,			/*!< FIREWALL PORT CLOSE NOTIFY */	
	NOTIFY_FIREWALL_PORT_CHANGE,		/*!< FIREWALL PORT CHANGE NOTIFY */	
	NOTIFY_FIREWALL_LOG_START,			/*!< FIREWALL LOG START NOTIFY */	
	NOTIFY_FIREWALL_LOG_STOP,			/*!< FIREWALL LOG STOP NOTIFY */	
	NOTIFY_FIREWALL_DELETE_OBJECT,		/*!< FIREWALL DELETE OBJECT NOTIFY */	
	NOTIFY_FW_VOIP_ALG_ENABLED,			/*!< FW VOIP ALG ENABLED NOTIFY */	
	NOTIFY_FW_VOIP_ALG_DISABLED,		/*!< FW VOIP ALG DISABLED NOTIFY */	
	NOTIFY_FW_FTP_ALG_ENABLED,			/*!< FW FTP ALG ENABLED NOTIFY */	
	NOTIFY_FW_FTP_ALG_DISABLED,			/*!< FW FTP ALG DISABLED NOTIFY */	
	NOTIFY_FW_TFTP_ALG_ENABLED,			/*!< FW TFTP ALG ENABLED NOTIFY */	
	NOTIFY_FW_TFTP_ALG_DISABLED,		/*!< FW TFTP ALG DISABLED NOTIFY */	
	NOTIFY_FW_PPTP_ALG_ENABLED,			/*!< FW PPTP ALG ENABLED NOTIFY */	
	NOTIFY_FW_PPTP_ALG_DISABLED,		/*!< FW PPTP ALG DISABLED NOTIFY */	
	NOTIFY_FW_IPSEC_ALG_ENABLED,		/*!< FW IPSEC ALG ENABLED NOTIFY */	
	NOTIFY_FW_IPSEC_ALG_DISABLED,		/*!< FW IPSEC ALG DISABLED NOTIFY */	
	NOTIFY_DEFAULT_USBNET_ADD,			/*!< DEFAULT USBNET ADD NOTIFY */	
	NOTIFY_DEFAULT_USBNET_REMOVE,		/*!< DEFAULT USBNET REMOVE NOTIFY */	
	NOTIFY_WAN_ADD,						/*!< WAN ADD NOTIFY */
	NOTIFY_WAN_DEL,						/*!< WAN DEL NOTIFY */
	NOTIFY_WAN_MODIFY,					/*!< WAN MODIFY NOTIFY */
	NOTIFY_INTERFACE_STATUS_SLMSG,		/*!< INTERFACE STATUS SLMSG NOTIFY */
	NOTIFY_IPADDRESS_CHANGE_SLMSG,		/*!< IPADDRESS CHANGE SLMSG NOTIFY */
	NOTIFY_DHCP_CLIENT_UP,				/*!< DHCP CLIENT UP NOTIFY */
	NOTIFY_DHCP_CLIENT_DOWN,			/*!< DHCP CLINET DOWN NOTIFY */
	NOTIFY_DHCP_DNSMASQ_DELALL,			/*!< DHCP DNSMASQ DELALL */
	NOTIFY_IPv6_RDNSS,					/*!< IPv6 RDNSS NOTIFY */
	NOTIFY_IPv6_DNSSL,					/*!< IPv6 DNSSL NOTIFY */
	NOTIFY_PPP_UP,						/*!< PPP UP NOTIFY */
	NOTIFY_PPP_DOWN,					/*!< PPP DOWN NOTIFY */	
	NOTIFY_DYNAMIC_6RD,					/*!< DYNAMIC 6RD NOTIFY */
	NOTIFY_DSLITE_AFTER,				/*!< DSLITE AFTER NOTIFY */
	NOTIFY_DSLITE_HOSTNAME,				/*!< DSLLITE HOSTNAME NOTIFY */
	NOTIFY_NETIFD_IPADDRESS_ADD,		/*!< NETIFD IPADDRESS ADD NOTIFY */	
	NOTIFY_NETIFD_IPADDRESS_REM,		/*!< NETIFD IPADDREESS REM NOTIFY */
	NOTIFY_WAN_UP,						/*!< WAN UP NOTIFY */
	NOTIFY_WAN_DOWN,					/*!< WAN DOWN NOTIFY */
	NOTIFY_TEST,						/*!< TEST NOTIFY */
	NOTIFY_QOS_ENABLED,					/*!< QOS ENABLED NOTIFY */
	NOTIFY_QOS_DISABLED,				/*!< QOS DISABLED NOTIFY */
	NOTIFY_LTE_WAN_ENABLED,				/*!< LTE WAN ENABLED NOTIFY */
   	NOTIFY_LTE_WAN_DISABLED,			/*!< LTE WAN DISABLED NOTIFY */
	NOTIFY_SYS_UPDATE,					/*!< SYS UPDATE NOTIFY */
	NOTIFY_SYS_PPA_INIT,				/*!< SYS PPA INIT NOTIFY */
	NOTIFY_SYS_PPA_INTF_ADD,			/*!< SYS PPA INTF ADD NOTIFY */
	NOTIFY_SYS_PPA_INTF_DEL,			/*!< SYS PPA INTF DEL NOTIFY */
	NOTIFY_SYS_PPA_ENABLE,				/*!< SYS PPA ENABLE NOTIFY */
	NOTIFY_ETH_MODULE_LOAD_COMPLETE,	/*!< ETH MODULE LOAD COMPLETE NOTIFY */
	NOTIFY_ETH_BOND_INTERFACE_REGISTRATION,	/*!< ETH MODULE BOND INTERFACE STATUS NOTIFY */
	NOTIFY_AUTOWAN_NETWORK_AUTOWAN_DIAGNOSTICS,	/*!< NOTIFY_AUTOWAN_NETWORK_AUTOWAN_DIAGNOSTICS */
	NOTIFY_NETWORK_AUTOWAN_AUTOWAN_STATUS,	/*!< NOTIFY_NETWORK_AUTOWAN_AUTOWAN_STATUS */
	NOTIFY_DEFAULT_WAN_CHANGE,				/*!< DEFAULT WAN CHANGE NOTIFY */
	NOTIFY_DEFAULT_LAN_MODIFY,				/*!< DEFAULT LAN MODIFY NOTIFY */
	NOTIFY_IPV6_NEW_PREFIX,					/*!< IPV6 NEW PREFIX NOTIFY*/
	NOTIFY_IPV6_NEW_PREFIX_UPDATE,			/*!< IPV6 NEW PREFIX UPDATE NOTIFY*/
	NOTIFY_STATIC_DNS_CHANGE,				/*!< STATIC DNS CHANGE NOTIFY*/
	NOTIFY_TC_CHANGE,						/*!< TC NOTIFY*/	
	NOTIFY_LOOPBACK_UP, 					/*!< LOOPBACK UP NOTIFY*/
	NOTIFY_LOOPBACK_DOWN, 					/*!< LOOPBACK DOWN NOTIFY*/
	NOTIFY_L2_IFACE_ADD, 					/*!< L2 IFACE ADD NOTIFY*/
	NOTIFY_L2_IFACE_REM, 					/*!< L2 IFACE REM NOTIFY*/
	NOTIFY_SYSLOG_VIEWER,                                   /*!< SYSLOG VIEWER WEB NOTIFY*/
	NOTIFY_BRIDGED_WAN_UP,                                /*!< BRIDGED WAN UP NOTIFY*/
	NOTIFY_BRIDGED_WAN_DOWN,                                /*!< BRIDGED WAN DOWN NOTIFY*/
	NOTIFY_BRIDGED_WAN_ADD,                                /*!< BRIDGED WAN ADD NOTIFY*/
	NOTIFY_BRIDGED_WAN_DEL,                                /*!< BRIDGED WAN DEL NOTIFY*/
	NOTIFY_FW_UPGRADE,                                   	/*!< FW UPGRADE NOTIFY*/
	NOTIFY_FW_UPGRADE_PRE_DL,                               /*!< FW UPGRADE BEFORE DL NOTIFY*/
	NOTIFY_FW_UPGRADE_POST_DL,                              /*!< FW UPGRADE AFTER DL NOTIFY*/
	NOTIFY_FWUPGRADE_STATUS,				/*!< FW UPGRADE STATUS MESSAGE NOTIFY TO WSD */
	NOTIFY_WPS_STATUS,					/*!< WPS STATUS MESSAGE NOTIFY TO WSD */
	NOTIFY_AUTOWAN_STATUS,					/*!< AUTOWAN STATUS MESSAGE NOTIFY TO WSD */
	NOTIFY_ALL_INIT_COMPLETED,                              /*!< Notify when all SL's INIT operation completed by Servd */
	NOTIFY_LW4O6_UP,					/*!<Stateless DSLite UP event  */
	NOTIFY_LW4O6_DOWN,					/*!<STateless DSLite DOWN event  */
	NOTIFY_IFACE_DELETE,					/*!< PPP interface down NOTIFY */
	NOTIFY_VLAN_CONFIG,					/*!< WAN VLAN ID add/remove NOTIFY */
	NOTIFY_DSL_STATUS,		/*!< DSL INTERFACE NOTIFY */
	NOTIFY_DSL_SWITCHOVER,					/*!< DSL Switchover load/unload NOTIFY */
	NOTIFY_WANMODE_CHANGE,					/*!< WAN Mode Change NOTIFY */
	NOTIFY_GR909_EXE_TEST,					/*!< GR909 TEST start NOTIFY */
	NOTIFY_DECT_XRAM_TEST,					/*!< XRAM Memory GET/SET NOTIFY */
	NOTIFY_DECT_TBR6_TEST,					/*!< DECT TBR6 START/STOP TEST NOTIFY*/
	NOTIFY_DECT_TPC_TEST,					/*!< DECT TPC GET/SET NOTIFY*/
	NOTIFY_IPV6_ADD,                                        /*!< IPV6 ADD NOTIFY*/
	NOTIFY_IPV6_DEL,                                        /*!< IPV6 DEL NOTIFY*/
	NOTIFY_UPNP_UPDATE_REQ,                                 /*!< UPNP UPDATE NOTIFY*/
	NOTIFY_UPNP_ROUTE_ADD,                                  /*!< UPNP ADD ROUTE*/
	NOTIFY_UPNP_ROUTE_DEL,                                  /*!< UPNP Delete ROUTE*/
	NOTIFY_MWAN_INFO,					/*!< Multiwan Info NOTIFY*/
	NOTIFY_MWAN_UP,						/*!< Multiwan WAN Up NOTIFY*/
	NOTIFY_MWAN_DOWN,					/*!< Multiwan WAN Down NOTIFY*/
	NOTIFY_MWAN_REQ_DEFWAN_CHANGE,				/*!< Default WAN Chnage request from Multiwan*/
	NOTIFY_DECT_MODEM_RESET,                /*!< DECT MODEM RESET NOTIFY*/
	NOTIFY_FACTORY_RESET,					/*!< Factory reset notification*/
	NOTIFY_BRIDGE_ADD,					/*!< Bridge Add NOTIFY*/
	NOTIFY_BRIDGE_DEL,					/*!< Bridge Delete NOTIFY*/
	NOTIFY_BRIDGE_MODIFY,					/*!< Bridge Modify NOTIFY*/
	NOTIFY_BRIDGE_UP,					/*!< Bridge up NOTIFY*/
	NOTIFY_BRIDGE_DOWN,					/*!< Bridge down NOTIFY*/
	NOTIFY_DYNDNS_STATUS_UPDATE,				/*!< 134 used by ez-ipupdate to update status*/
	NOTIFY_FORCE_DEFAULT_WAN,				/*!< Forcibly change default WAN */
	NOTIFY_TEST_FEATURE_SL1,				/*!< ServD test Feature SL sample notification */
	NOTIFY_TEST_APP_SL1,					/*!< ServD test App SL sample notification */
	NOTIFY_USB_DEVICE_CONNECTED,				/*!< USB CONNECTED NOTIFICATION */
	NOTIFY_USB_DEVICE_MOUNTED,				/*!< USB MOUNTED NOTIFICATION */
	NOTIFY_BOOST_INIT,					/*! Device prioritization init notification */
	NOTIFY_BOOST_UNINIT,					/*! Device prioritization uninit notification */
	NOTIFY_WMS_REGISTRATION,				/*! Register with WAN Metrics Service (WMS) */
	NOTIFY_WMS_DEREGISTRATION,				/*! Deregister from WAN Metrics Service (WMS) */
	NOTIFY_WMS_MODIFY,					/*! Modify registered WAN Metrics Service (WMS) parameters */
	NOTIFY_WMS_STATUS,					/*! Send WAN Metrics Service (WMS) notification */
	NOTIFY_WIFI_BRIDGE_RELOAD,				/*!< WIFI BRIDGE RELOAD NOTIFICATION */
	NOTIFY_WIFI_WLAN_INIT,				/*! NOTIFY_WIFI_WLAN_INIT */
	NOTIFY_WIFI_WLAN_HW_INIT_DONE,				/*!< NOTIFY_WIFI_WLAN_HW_INIT_DONE */
	NOTIFY_CONFIG_RESTORE,					/*!< CONFIGURATION RESTORE NOTIFY*/
	NOTIFY_FIREWALL_RULES,					/*!< Update firewall rules Notification */
	NOTIFY_WIFI_WPS_ENDPOINT_DONE,			/*!< NOTIFY_WIFI_WPS_ENDPOINT_DONE*/
	__NOTIFY_DEFS_TOTAL_COUNT				/*!< TOTAL COUNT of NOTIFY enums */
} NotifyDefs;

/* @} */
#endif /* _UGW_NOTIFY_DEFS_H */
