#!/bin/sh /etc/rc.common

/etc/preinit.d/scapi_utils.sh
USE_PROCD=1
START=11

start_service() {
        file="/tmp/lighttpd5.conf"
        if [ -f "$file" ]
        then
            echo "$file exist."
        else
            cp /opt/vendor/www2/lighttpd5.conf "$file"
        fi
        procd_open_instance
        procd_set_param command lighttpd -D -f "$file"
        procd_set_param respawn
        procd_close_instance
}