#!/bin/sh /etc/rc.common

/etc/preinit.d/scapi_utils.sh
USE_PROCD=1
START=11

start_service() {
        if ! [ -f "/dev/tap0" ]; then cp /dev/null /dev/tap0; fi
        procd_open_instance
        procd_set_param command openvpn /tmp/openvpn/server_tap.conf
        procd_set_param respawn
        procd_close_instance
}

